"""add description to products

Revision ID: 89b7148702f9
Revises: 0001
Create Date: 2026-05-14 10:10:13.564480
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '89b7148702f9'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index('ix_products_internal_code', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_internal_code', 'products', ['internal_code'], unique=False)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
